vich_uploader:
    db_driver: orm

    mappings:
        users_images:
            uri_prefix: '%app.path.image_uploads%'
            upload_destination: '%kernel.project_dir%/public/users_upload/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: false
