version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./back:/var/www/html
    ports:
      - "8437:8437"
    depends_on:
      - backend

  backend:
    build:
      context: ./back
    container_name: picshack-backend
    volumes:
      - ./back:/var/www/html
    ports:
      - "9999:9999"
    environment:
      DATABASE_URL: mysql://user:password@mysql:3306/picshack
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "php", "-r", "try { new PDO(getenv('DATABASE_URL')); exit(0); } catch (Exception $e) { exit(1); }"]
      interval: 10s
      retries: 5

  frontend:
    build:
      context: ./front
    container_name: picshack-frontend
    ports:
      - "5555:5555"

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: pickshack
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "user", "-p password"]
      interval: 10s
      retries: 5

volumes:
  mysql-data:
